language: node_js
node_js:
  - 12.13.0
install:
  - npm install  
script:
  - npm run test
deploy:
  local_dir: dist
  provider: pages
  edge: true
  skip_cleanup: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master