language: node_js
node_js:
  - 7
brunches:
  only:
    - master
after_success:
  - echo "Hola"      

deploy:
  local_dir: dist
  provider: pages
  edge: true
  skip_cleanup: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master